app_deployment:
  appName: tolkien-ai-server
  image: nexus-docker-craigmiller160.ddns.net/expense-tracker-api:latest
  configMap:
    spring.profiles.active: prod
    tolkienai.weaviate.host: weaviate-service.infra-prod
    openapi.server: https://tolkien-ai.craigmiller160.us
    spring.data.mongodb.database: tolkienai_prod
    spring.data.mongodb.host: mongodb.infra-prod
    spring.data.mongodb.port: 27017
  onepassworditems:
    - name: openai-key
      itemPath: vaults/Home Server (Prod)/items/OpenAI Key
    - name: weaviate-key
      itemPath: vaults/Home Server (Prod)/items/Weaviate API Key
    - name: mongo-root-account
      itemPath: vaults/Home Server (Prod)/items/MongoDB Root Account
  ports:
    - containerPort: 8080
  secrets:
    - envVariable: spring.data.mongodb.username
      secretName: mongo-root-account
      secretKey: username
    - envVariable: spring.data.mongodb.password
      secretName: mongo-root-account
      secretKey: password
    - envVariable: tolkienai.openai.key
      secretName: openai-key
      secretKey: password
    - envVariable: tolkienai.weaviate.key
      secretName: weaviate-key
      secretKey: password
  commonProbe:
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTP