tolkienai:
  weaviate:
    host: craigpc:30000
    class-name: Tolkienai_dev

openapi:
  server: http://localhost:8080

spring:
  data:
    mongodb:
      database: tolkienai_dev
      host: craigpc
      port: 30021

  security:
    keycloak:
      oauth2:
        resourceserver:
          realm: apps-dev

logging:
  level:
    us.craigmiller160.tolkienai.server: DEBUG
    org.springframework.data.mongodb: DEBUG
    us.craigmiller160.tolkienai.server.data.Logger: TRACE
    io.weaviate: DEBUG