tolkienai:
  weaviate:
    host: craigpc:30000
    scheme: https
  openai:
    timeouts:
      connect-seconds: 10
      socket-seconds: 30
      request-seconds: 120
  raw-sources:
    silmarillion: /Users/craigmiller/Documents/silmarillion_raw.txt

spring:
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@craigpc:30021/${spring.data.mongodb.database}?ssl=true&authSource=admin
      database: tolkienai_dev
