tolkienai:
  weaviate:
    host: craigpc:30000
    scheme: https
  openai:
    timeouts:
      connect-seconds: 10
      socket-seconds: 30
      request-seconds: 120
  raw-sources:
    silmarillion:
      path: /Users/craigmiller/Documents/silmarillion_raw.txt
      exclude-lines:
        - 1-238
        - 16016-16410

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@craigpc:30021/${spring.data.mongodb.database}?ssl=true&authSource=admin
      database: tolkienai_dev

  security:
    keycloak:
      oauth2:
        resourceserver:
          host: https://auth.craigmiller160.us
          realm: apps-dev
          client-id: tolkien-ai-server

logging:
  level:
    us.craigmiller160.tolkienai.server: DEBUG
