tolkienai:
  weaviate:
    scheme: https

  openai:
    timeouts:
      connect-seconds: 10
      socket-seconds: 30
      request-seconds: 120
    models:
      embedding:
        name: text-embedding-3-large
        dimensions: 3072
      chat:
        name: gpt-3.5-turbo-0125

  raw-sources:
    silmarillion:
      path: ${user.dir}/raw/silmarillion.txt
      exclude-lines:
        - 1-238
        - 16016-16410

  chat:
    query:
      record-limit: 10

spring:
  data:
    migrations:
      enabled: true
      mongo:
        migration-paths:
          - classpath:us/craigmiller160/tolkienai/server/data/migration/mongo/migrations
      weaviate:
        migration-paths:
          - classpath:us/craigmiller160/tolkienai/server/data/migration/weaviate/migrations

  security:
    keycloak:
      oauth2:
        resourceserver:
          host: https://auth.craigmiller160.us
          client-id: tolkien-ai-server

logging:
  level:
    root: INFO