tolkienai:
  weaviate:
    host: craigpc:30000
    scheme: https
  openai:
    timeouts:
      connect-seconds: 10
      socket-seconds: 30
      request-seconds: 120

spring:
  data:
    mongodb:
      uri: mongodb://craigpc:30021/${spring.data.mongodb.database}?ssl=true
      authentication-database: admin
      database: tolkienai_dev
